version: '3'
services: 

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  web:
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - db
    ports:
      - '4000:3000'
volumes:
  pgdata:
